# Generated by Django 6.0.4 on 2026-04-30 05:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='от 1 до 10000', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Номер столика')),
                ('image', models.ImageField(blank=True, max_length=256, null=True, upload_to='table/%Y/%m', verbose_name='Изображение столика')),
                ('seats', models.IntegerField(help_text='от 0 до 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Кол-во мест за столиком')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата бронирования')),
                ('hour_start', models.IntegerField(help_text='от 8 до 17', validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(17)], verbose_name='Час начала бронирования')),
                ('hour_end', models.IntegerField(help_text='от 9 до 18', validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(18)], verbose_name='Час окончания бронирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания бронирования')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='table_reservation.table')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
