# Generated by Django 6.0.4 on 2026-04-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0002_table_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
