# Generated by Django 6.0.4 on 2026-05-20 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название события')),
                ('description', models.TextField(blank=True, verbose_name='Описание события')),
                ('city', models.CharField(default='Минск', max_length=100, verbose_name='Город')),
                ('meeting_time', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('category', models.CharField(choices=[('dance', 'Танцы'), ('party', 'Вечеринка'), ('hike', 'Поход'), ('other', 'Другое')], max_length=10, verbose_name='Категория')),
                ('users', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'ordering': ['meeting_time'],
            },
        ),
    ]
